sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: LnjMLiOMChK0EuC93ya4/yOTSm0zv/R9/a5a5ecg1tdnEZgBm58HmJo7q/VWeKRyti5u4zoVv7QQqeb6Z+Aho2mO8Fr6d2zGE9EQGdZZUoYOjLsXvp2+XDJqiMYvpueMEIicPu+KcwV/OBAgso5ZJiGPCwwr0otg60gdnNAAwJ3b964FgJ1aPzok6p41olIn8TvA5l4C6LLlhsyNxwE9yrHYGLIZWIAxFO19bOm14gXB6jxmqdzQiCPRexbHxxi4yRJ45rP9HYxs9+h5L2iMbEoC6STi3SvYyg3U7HTxGjPYM/9+LmabLKPZBfT5bmct/lF5JjXsDojW+XnpzmOGSvoCmBaBPzk6lU+A47V2MiEl3AeUDzg6zR/hYtMZKj606LgpYEZXW9H1LnZ/iyCwwU6NP5F0LTPKCZ1WS64u0T7riR8KuShFScPELkn63s+UlNQOCkfq3GMHsdtUCBbSiqbsKNozhrdE3CifupNklkh/IMb5hB/5HcOiCbpn4q++NvST0E6FYTew7ebQ45v+UoXAaRev+GzhUq4VQUHCfP5F2kQQh5Waa+bcx1A5HWxoFFUoFvbm1JbOHCCFRylZnstI7i6Xiwm93WldbfZStyDJ3n2d0Qo1UX6QxttwsJiFW8YDmGj2GGztC2aulFiI3MoASLQeSEolE9w1Bj8RJ+k=
  - secure: bvEF66XhM4y53sM2Jf7orjfajInAetq9jD59U60TeLXBgeNffGLaBD3CcUEA+JfnQYpqB0uI1jXMenrFzs8gUErxiJx/2FhO97pk7bJor/0342HSO/p1VU7jjFOniansYQ0vMwGdak1dwCQp9xFMHwRlyLUklRAFxlhglCDi7pJKjYQwDJM0DH64AQLSIgLOT7zvYCoZ42WxHYO56qMuiTqd9XugR3Rp3v7bLDJoQYtqAfAvjg8xD6V3FEwZ5SsBAQuoWhAwi0FOrEBsl0GDaeUXOK7QqOX+y6WFbcQYCbHH24UmetjNIwWR3eDIloJvd3gb4Zv17/ncUzs65LnOixmE0kNaJSABKEv2lmFzTo6IRCl9xcczsfUtMAAdBO+HHJaBpPorn98QJ25OfNu2pi8sdlvLsXT2hVhf+Z+r1dR0F3wqsi/kuV846ic6NHK+d7yz5BVwFaPmylKVRA02JoHdbr/Hted7/S98kmbTgd9gFoxhbAmBBPo5caGH3S0zFpVVslZFrCnGZK9KbWMTKBVZaiuo7PKi1itJa7wI7RjeaiZ1jaf7slAMs4qQBmVKkKv81gmt2YKHr3drUp25ajP6onxge5iU9e4EEzX8Zg1IzPc7RpW3I+UC3BHW5sUhbsygvEUZzisWsG1Zk5xOdThYwoLgvT/TfsmX/e5V1Eg=
  - secure: UCVTo6zws63V4AM1a/Ylxg5WEsP6pBPEhpCHqp3eesUG/aFVDnwRKrT9Is7IPfqeCQAkqY2fLrbTGp9yBGCGIH/xWCmwT05UHag53eBkITncIk+RM0r54Juqhc8EivLJCLTVrZM4UVT27kkqjTTuEbc0Ik/QW3PumUuTqcl62rljRGWE4quxVh6xTKcA/LHThMXocMnfBL5gPNXmkn0c65JZb/l33vN7Ee9H+3/ll6TzIRtB4wWxYO86kxEeuOSSHB/uA3sHMb/hOZzj9+lr81pv/Z0yqiLCq1vNZAMwTdklY6qBFpU6NiMynnFT4EzAEY62Yisvajo+2zN/sehb1XaYqFNoAqHO5m1ess2R4o4VweSSWvXFMGuqTDk/TjPAYZiYl3+mMd/6mI5lhqi/GPf/eouIhpGnvUWOkEqKWjFkbxlaOl2Gyl03hOmnwrCqDKH3x2Bf3E3lGuovbDot/WN9xMbpPbM1eMsya+ffBB88OhYntC3qpsg5ODscSvHRn6xI2IMC5xVVVtnIPZ1ol0jWCs0zdDhvxYU5OqrH5NxcukpLGDUt7n00dfYp8CNlfm6qPVgM7U18hyhYNGtUbkxGhnO5vuTNx5MZDvTi6J092HoUlWBCJIZQKLFIyGlf/C1fVkdrP71SG3EXq9PxTVImH5RGPneWQxSlSjkUbTA=
  - secure: Ul/kLsJdCMKylR0FmPb/8iI209DjnJe57c+0FGTZ6zZbEcBWb9ADrKuEHqkQmca7DJ1mi9pXOUFmxljUgrrtKwAk+8hEVw3UzydQB++V02vdIrQD0/RbCJfYX1HphGjek1nZmlWET2kAk32TT1YUat/3fmOXcLT9mfaSf2ErUizBhgXa73pqGVgKf89bICdOSxyRU6bQVsEVslnNkBRi8q+dRLsCvnVz9lUqSjBDPdDfkF5wnHEM+GBtzozKuUo7LAuxX4W24NkuhrglvbLGB2tjHNGd7qzZGtg07+SrZ4kZRxWE61mytH5xTllNpTLkNLjLBINxXQ+OzPuhJw7yo/OpL7FdHo5MRWuasVkDaVOPzAXKBAFEZiy77s7vWIwF2YutS12717sWyGf8VpwOHQ+IaWutjnqP500dzlniE0+pN7L234nHt3jizpX2bNMl/smnULKSFJC+lPMxxDnEGme6QdFjMilbU9PkRYFHC7ODY6rotloP6YEKW1PTwIBiG4ktuuhBK5Jl+qj4DVB94AYm+JrzZdmS4ZXogesY5qpibOC4WKB56zU6eJLUlHit99kxaeCNbe6M7+VUYTQaHadwSxRM+II9/ZRyi+27fJqjBL7jiZILqzXYE5HgxOYZp49fxcvdhOAlqVGhVk7m1K1Tyg9sPQZq6nDPOW5rAM0=
cache:
  directories:
    - $HOME/.m2
before_install:
- cp .settings.xml $HOME/.m2/settings.xml
after_success:
- mvn coveralls:report
before_deploy:
- openssl aes-256-cbc -K $encrypted_7ff839c9437b_key -iv $encrypted_7ff839c9437b_iv
  -in .sign.asc.enc -out .sign.asc -d
- gpg2 --fast-import .sign.asc
- export GPG_TTY=$(tty)
deploy:
  provider: script
  script: mvn deploy
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: C6KGLt70oADRQlIGqaYim4cAaiZP+DcgUm2kW3cqTsqD/9havMi1h2JwNqKBPl21P32xBvKwjU15Nx1niQ8EctlcfF7DOhjlpOWb/1b5YRQaydgjDwiOkNOAQ/MzfvGO7ssD/YyjRbwzaC4R/XudrdDyPiXSttplIw91596sVmb2wVfD8EOJTgsT6fq+l23wF1fEHl79VL5PKXqkCDp82xWJePTqolmF07QXY2o8eONb6RlykyBZiWi+L+87/eVTptflyvUoMcNC9N4WmIzDAXQ8+dRQMHSBgZLCjtSR5/6qQeZD4d0BCzlAELjspTeChbSOMQszjjY7JbrNegQ6EJ1OVg6YqJuTIdhgKO0D6IJnuTV4IgTOSauJC2d+W1tNThSi4Q7jSifP+1/ynT4Ji/DiCS9z4sqOtpoSfMtDl1YwMDkXHlpkppfKyjyQl4YjWkU3JMT9vVfj2FN8JhwdrE49CgyOG4EAjDFhDvDfFzdZaI83OZC4XrBoguhHU1HVQzrniq43ZWkezVOujOslQ1JkUr6DM06cRSlmnCIYTMkp7j2RyZDgsupi45/JMlzejZDCG2DIjkRIWxD+ZSjXHUvI19si+YM5u93z10NLZaqJ49Do2v/iQteftYYFhITh+uiCPtsMEnbYffo23K6KuXlIkKF11GBfNbPuDNZc5Io=
    on_success: change
    on_failure: always
