version: 2.1

executors:
  maven:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    executor: maven
    steps:
      - checkout
      - restore_cache:
          key: jira-confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Download uncached Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jira-confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Compile, Package and Test
          command: mvn package
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
  deploy:
    executor: maven
    steps:
      - checkout
      - restore_cache:
          key: jira-confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Download uncached Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jira-confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Decrypt Signing Key
          command: openssl aes-256-cbc -S ${SIGN_ASC_SALT} -K ${SIGN_ASC_KEY} -iv ${SIGN_ASC_IV} -in .circleci/sign.asc.enc -out .circleci/sign.asc -d
      - run:
          name: Import Signing Key
          command: gpg2 --fast-import .circleci/sign.asc
      - run:
          name: Export GPG Shell
          command: export GPG_TTY=$(tty)
      - run:
          name: Deploy to Maven Central
          command: mvn -s .circleci/settings.xml -DskipTests deploy

workflows:
  main:
    jobs:
      - build:
          context: global
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
          context: deploy-maven
