version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: jira-confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Download uncached Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jira-confapi-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Compile, Package and Test
          command: mvn package
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  main:
    jobs:
      - build:
          context: global
